version: '3'
services:
  web:
    image: crowdfundadmin:v0.0.8
    expose:
      - '8000'
      - '9000'
      - '5555'
    ports:
      - '8000:8000'
      - '9000:9000'
      - '5555:5555'
    volumes:
      - '.:/code'
    stdin_open: true
    tty: true
    entrypoint: '/entrypoint.sh'
    command: supervisord -c ./supervisord.conf --nodaemon
    env_file: .env
