# Generated by Django 2.1.1 on 2018-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='public_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='verto_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='whitelist_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
